[BACKPORT] Fix nix build since cartero now expects updated rust version (#207)
This PR addresses an issue on the nix build that appeared after some
packages required more recents versions of rustc to be able to build the
project, the error looks like this:
```
$ nix build '.#default'
error: builder for '/nix/store/rd2vr1rvqs49qinchk7fkni54lsnpljv-cartero-git.drv' failed with exit code 1;
       last 25 log lines:
       > [7/19] Building translation po/fr/LC_MESSAGES/cartero-fr.mo
       > [8/19] Building translation po/gl/LC_MESSAGES/cartero-gl.mo
       > [9/19] Building translation po/pt/LC_MESSAGES/cartero-pt.mo
       > [10/19] Building translation po/pt_BR/LC_MESSAGES/cartero-pt_BR.mo
       > [11/19] Building translation po/ro/LC_MESSAGES/cartero-ro.mo
       > [12/19] Building translation po/ru/LC_MESSAGES/cartero-ru.mo
       > [13/19] Building translation po/ta/LC_MESSAGES/cartero-ta.mo
       > [14/19] Merging translations for data/es.danirod.Cartero.desktop
       > [15/19] Merging translations for data/es.danirod.Cartero.appdata.xml
       > [16/19] Generating data/blueprints with a custom command
       > [17/19] Generating data/cartero_gresource with a custom command
       > xml-stripblanks preprocessing requested, but XMLLINT is not set, and xmllint is not in PATH
       > [17/19] Generating src/cargo-build with a custom command (wrapped by meson to set env)
       > warning: `/build/.cargo/config` is deprecated in favor of `config.toml`
       > note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
       > error: rustc 1.78.0 is not supported by the following packages:
       >   litemap@0.7.5 requires rustc 1.81
       >   zerofrom@0.1.6 requires rustc 1.81
       > Either upgrade rustc or select compatible dependency versions with
       > `cargo update <name>@<current-ver> --precise <compatible-ver>`
       > where `<compatible-ver>` is the latest version supporting rustc 1.78.0
       >
       > FAILED: src/release
       > env CARGO_HOME=/build/sa73n12wlcshxb1wkbfgr6idd0b548hd-source/build/cargo-home /nix/store/kshky69v2yk4id89xdq649rymyx6cn8n-cargo-1.78.0/bin/cargo build --manifest-path /build/sa73n12wlcshxb1wkbfgr6idd0b548hd-source/Cargo.toml --target-dir /build/sa73n12wlcshxb1wkbfgr6idd0b548hd-source/build/src --release --no-default-features --features csd
       > ninja: build stopped: subcommand failed.
       For full logs, run:
         nix log /nix/store/rd2vr1rvqs49qinchk7fkni54lsnpljv-cartero-git.drv
```

What this PR does is accept appropiate rustc & cargo packages on the
derivation parameters, and then builds the project using those versions,
i also used the [oxalica's](https://github.com/oxalica/rust-overlay) to
pull newer versions of rustc and cargo as [recommended by the nix
documentation on rust
packaging](https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/rust.section.md#using-rust-nightly-in-a-derivation-with-buildrustpackage-using-rust-nightly-in-a-derivation-with-buildrustpackage)